# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_auto_20180115_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
